# Generated by Django 5.0.5 on 2024-05-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('chats', '0002_alter_message_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='topic',
        ),
        migrations.AddField(
            model_name='blog',
            name='topic',
            field=models.ManyToManyField(to='chats.topic'),
        ),
    ]
