# Generated by Django 5.0.5 on 2024-05-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogchatuser',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='blogchatuser',
            name='hobbies',
            field=models.ManyToManyField(related_name='users', to='accounts.hobby'),
        ),
    ]
